/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FootMusic: typeof import('./src/components/MusicItem/FootMusic.vue')['default']
    IconList: typeof import('./src/components/home/IconList.vue')['default']
    MLIList: typeof import('./src/components/MusicItem/MLIList.vue')['default']
    MLITop: typeof import('./src/components/MusicItem/MLITop.vue')['default']
    MusicDetail: typeof import('./src/components/MusicItem/MusicDetail.vue')['default']
    MusicList: typeof import('./src/components/home/MusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperTop: typeof import('./src/components/home/SwiperTop.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
